# Generated by Django 3.2.8 on 2021-10-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileserver',
            old_name='attachments',
            new_name='file',
        ),
    ]
